apiVersion: v1
kind: ConfigMap
metadata:
  name: services-config
  namespace: default
data:
  # Service Ports
  BACKEND_PORT: "3000"
  FRONTEND_PORT: "80"
  AI_SERVICE_PORT: "8000"

  # Node Environment
  NODE_ENV: "production"

  # CORS / Frontend URL
  FRONTEND_URL: "http://a7f9e0e6ea184484293bae10ac1e11b1-2112241700.us-east-1.elb.amazonaws.com"
  CLIENT_ORIGIN: "http://ac8aa29ece4be4e1a9eeb420c97589b7-2030314384.us-east-1.elb.amazonaws.com,http://aneessaheba.shop,https://aneessaheba.shop"
  ALLOW_ALL_CORS: "true"
