apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector: { matchLabels: { app: backend } }
  template:
    metadata: { labels: { app: backend } }
    spec:
      containers:
        - name: backend
          image: dohyeong99/lab2-backend:v1   # or your local image if on Minikube
          env:
            - { name: PORT, value: "4000" }
            - { name: DB_HOST, value: "mysql" }
            - { name: DB_USER, value: "root" }
            - { name: DB_PASSWORD, value: "root" }
            - { name: DB_NAME, value: "lab1" }
            - { name: KAFKA_BROKERS, value: "redpanda:9092" }
            - { name: MONGO_URI, value: "mongodb://mongo:27017/airbnb_db" }
            - { name: REDIS_URL, value: "redis://redis:6379/0" }
            # add any API keys as Secrets later if needed
          ports: [ { containerPort: 4000 } ]
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: { app: backend }
  ports:
    - port: 4000
      targetPort: 4000
